### ISSUE TITLE
ElasticSearch does not work with Vertexium 

### ISSUE THREAD

**Issue by nikhilsmotra** [v5analytics/vertexium#100]
It seems that the example provided at URL https://github.com/v5analytics/vertexium for API usage example to create AccumuloGraph does not use ElasticSearch by default. 

I am using the following configuration to use create AccumuloGraph to ensure that ElasticSearch indexes are being used while saving data or retrieving data from Graph. I am using ElasticSearch version 1.4.5

_Map mapConfig = new HashMap();
mapConfig.put(AccumuloGraphConfiguration.USE_SERVER_SIDE_ELEMENT_VISIBILITY_ROW_FILTER, false);
mapConfig.put(AccumuloGraphConfiguration.ACCUMULO_INSTANCE_NAME, "instance_name");
mapConfig.put(AccumuloGraphConfiguration.ACCUMULO_USERNAME, "username");
mapConfig.put(AccumuloGraphConfiguration.ACCUMULO_PASSWORD, "password");
mapConfig.put(AccumuloGraphConfiguration.ZOOKEEPER_SERVERS, "localhost");
mapConfig.put("search", "org.vertexium.elasticsearch.ElasticsearchSingleDocumentSearchIndex");
mapConfig.put("search.indexName", "instance-graph");
mapConfig.put("search.indexEdges", "false");
mapConfig.put("search.locations", "172.xxx.xxx.xxx");
mapConfig.put("search.indicesToQuery", "instance-graph");
mapConfig.put("search.clusterName", "elasticsearch");
AccumuloGraphConfiguration graphConfig = new AccumuloGraphConfiguration(mapConfig);
Graph graph = AccumuloGraph.create(graphConfig);_

I am successfully able to insert a new vertex into the graph store. Let us assume that I have created a vertex with id=1 and property name="john",email="john@email.com"

I am successfully able to search for the stored vertex using vertex id (1 for this particular example). When I try to search for an already existing vertex using a property value (say name="john"), I do  not get any hit(s) from ElasticSearch. Sample code
_Query graphQuery = graph.query("", authorizations);
graphQuery.has("name", "john");
// zero vertices are returned
Iterable<Vertex> iterableVertices = graphQuery.vertices();_

Please note that if do not use ElasticSearch by commenting out all properties starting with "search" while instantiating MapConfig object in the code snipped above, I can search for vertices using either vertex id or a property value.
 
**Could one of the experts please throw some light on how to get past this issue?**

**Comment by joeferner** [comment]
Couple of things to try...
1. Make sure to call `graph.flush()` before the query. This will ensure the data has made it to ES.
1. In the query above leave out the `""` parameter or replace it with `"*"`
1. Try adding the following to your log4j.xml. This will log the JSON query sent to ES.

      <logger name="org.vertexium.query.Query.QUERY" additivity="false">
        <level value="TRACE" />
        <appender-ref ref="console" />
      </logger>

**Comment by nikhilsmotra** [comment]
Thanks Joe for the quick response. Replacing "" in the query with "*" did the trick. Appreciate your quick response.

Do you guys have any plans of moving to a later version of ElasticSearch? A lot of APIs/interfaces exposed by ElasticSearch have changed in newer releases and are no longer compatible with vertexium code. Just thought of asking this question.

**Comment by joeferner** [comment]
We have a branch for upgrading to 2.3.2 but we haven't had the time to properly QA it yet https://github.com/v5analytics/vertexium/tree/elasticsearch-2.3.2
